import {
  AlertTriangle,
  ArrowRight,
  BarChart3,
  Bell,
  Check,
  ChevronLeft,
  ChevronRight,
  Cloud,
  Command,
  CreditCard,
  Facebook,
  File,
  FileText,
  HelpCircle,
  Image,
  Instagram,
  Laptop,
  Linkedin,
  Loader2,
  Lock,
  Moon,
  MoreVertical,
  MousePointer,
  Plus,
  RefreshCw,
  Bot as Robot,
  Settings,
  Shield,
  Sun,
  Trash,
  Twitter,
  User,
  X,
  Zap,
  Headphones,
  Palette,
  Smile,
  Brain,
  FolderSync,
  LucideIcon,
  Languages,
  Network,
} from "lucide-react"

export type Icon = LucideIcon

export const Icons = {
  logo: Command,
  close: X,
  spinner: Loader2,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  trash: Trash,
  post: FileText,
  page: File,
  media: Image,
  settings: Settings,
  billing: CreditCard,
  ellipsis: MoreVertical,
  add: Plus,
  warning: AlertTriangle,
  user: User,
  arrowRight: ArrowRight,
  help: HelpCircle,
  sun: Sun,
  moon: Moon,
  check: Check,
  zap: Zap,
  shield: Shield,
  robot: Robot,
  refresh: RefreshCw,
  bell: Bell,
  cloud: Cloud,
  barChart: BarChart3,
  mouse: MousePointer,
  headphones: Headphones,
  lock: Lock,
  devices: Laptop,
  wifi: Shield,
  palette: Palette,
  twitter: Twitter,
  facebook: Facebook,
  instagram: Instagram,
  linkedin: Linkedin,
  brain: Brain,
  sync: FolderSync,
  smile: Smile,
  language: Languages,
  offline: Network
}
